### PR TITLE
Update templates

### PR DESCRIPTION
**Pull request by fatima-malik99**
Added a template for the communication.md file. From now on, all the meeting agendas will be added in this template.

### CODE REVIEW

**Review by MadiMalik — COMMENTED** [review]
I think the changes very good

**Review by MadiMalik — DISMISSED** [review]
This template is really great for planning our weekly meetings. Thank you, Fatima!

**Review by MadiMalik — APPROVED** [review]
I think the changes are good, but we still need to make them better

**Review by MadiMalik — CHANGES_REQUESTED** [review]
This file has multiple consecutive blank lines that need to be removed

**Review by MadiMalik — APPROVED** [review]

**Review by MadiMalik — APPROVED** [review]

**Review by MadiMalik — APPROVED** [review]

**Review by MadiMalik — DISMISSED** [review]

**Comment by Shahroz657** [comment]
Fix CI checks

**Review by mojtabafayyaz — APPROVED** [review]

**Pull request merged**
